(function(s){const value={
  "schemaVersion": 3,
  "targets": [
    "final.itemWriter.patch",
    "final.rewardWriter.patch",
    "quest.rewardGrant.patch",
    "domainItem.setAmount.patch",
    "tokenShop.purchase.trace",
    "appraisalExchange.purchase.trace",
    "domainTokenShopCommodity.setTotal.trace",
    "dialogue.FieldTalkBaseNode.startInAnimation.trace",
    "dialogue.FieldTalkBaseNode.startOutAnimation.trace",
    "dialogue.FieldTalkBaseNode.onEndInAnimation.trace",
    "lua.getGlobalFlag",
    "lua.setGlobalFlag",
    "lua.fireAchievementTrigger",
    "lua.isAchievementCompleted",
    "lua.changeReservedItemAmount",
    "lua.changeGimmickItemAmount",
    "lua.setMysteryItemAmount",
    "lua.helixChangeItemAmount",
    "lua.setAutoFeedMode",
    "lua.getAutoFeedMode",
    "lua.setAutoFeedWaitTimeLetter",
    "lua.setAutoFeedWaitTimeMinimum",
    "lua.getShowTalkSkipButtonTime",
    "lua.resetPlaySpeedAndAutoText",
    "lua.isTalking",
    "lua.changeItemAmount",
    "dialogue.native.page_jump_delay",
    "dialogue.native.talk_layer_run_auto_touch",
    "dialogue.native.still_talk_layer_run_auto_touch",
    "dialogue.native.get_auto_feed_mode",
    "dialogue.native.get_auto_feed_wait_time_letter",
    "dialogue.native.get_auto_feed_wait_time_minimum",
    "dialogue.native.action_timer_value",
    "dialogue.native.talk_ui_process_wait",
    "dialogue.native.talk_layer_touch_handler",
    "dialogue.native.rendering_checker",
    "battle.addPCExp.patch",
    "catScratch.total",
    "catScratch.namedCount",
    "item.global",
    "achievement.get",
    "achievement.dispatch",
    "userdata.push",
    "dialogue.renderChecker"
  ],
  "checks": [
    "injection.resolver",
    "injection.token_repository",
    "injection.token_repository_slot",
    "injection.token_assign",
    "injection.token_kind",
    "injection.base_change",
    "injection.ticket_writer",
    "injection.dynamic_cast",
    "injection.master_getter",
    "injection.type_getter",
    "injection.resource_gate",
    "injection.other_resources",
    "injection.sync_manager",
    "injection.sync",
    "injection.achievement_callback",
    "injection.achievement_eligible",
    "injection.achievement_refresh",
    "injection.achievement_release",
    "injection.achievement_owner_slot",
    "injection.initial_weapon",
    "injection.initial_armor",
    "injection.initial_equipment",
    "injection.unknown_factory",
    "injection.rtti",
    "injection.change_slot",
    "injection.token_pool",
    "injection.other_pool",
    "injection.amount_max",
    "injection.equipment_master",
    "injection.embedded_id",
    "injection.queue",
    "injection.character_ready_slot",
    "injection.character_bss_bounds",
    "injection.currency_writer",
    "injection.currency_exclusion",
    "injection.equipment_instances",
    "injection.pet_instances",
    "injection.buddy_instances",
    "injection.unknown_instances",
    "injection.pet_storage",
    "injection.pet_survivors",
    "injection.pet_creation_transaction",
    "injection.fish_pool",
    "injection.fish_storage",
    "injection.lottery_semantics",
    "injection.growth_semantics",
    "runtime.mp_cost",
    "runtime.mp_delta",
    "runtime.mp_current",
    "runtime.mp_max",
    "runtime.damage",
    "runtime.dungeon",
    "runtime.encounter",
    "runtime.ad_context",
    "runtime.team_context",
    "mass.currency_token",
    "mass.token_shop",
    "mass.appraisal_shop",
    "mass.canonical_label",
    "mass.state_lifetime",
    "director.delta",
    "models.missing_capture",
    "models.zero_match",
    "models.ambiguous_match",
    "models.moved_target",
    "models.unwind_extents",
    "models.unwind_gaps",
    "models.speed_math",
    "models.lua_registration_rows",
    "dialogue.layout_fields"
  ],
  "optionalTargets": [
    "lua.fireAchievementTrigger",
    "lua.isAchievementCompleted",
    "lua.setMysteryItemAmount",
    "lua.helixChangeItemAmount",
    "lua.setAutoFeedMode",
    "lua.getAutoFeedMode",
    "lua.setAutoFeedWaitTimeLetter",
    "lua.setAutoFeedWaitTimeMinimum",
    "lua.getShowTalkSkipButtonTime",
    "lua.resetPlaySpeedAndAutoText",
    "lua.isTalking"
  ],
  "runtimeChecks": [
    "Live objects and native ABI calls",
    "Actual additions/removals and instance identity",
    "Resource supply and memory pressure",
    "Save acknowledgement and persistence",
    "Android lifecycle and feature isolation",
    "ShadowHook install/disable/unhook",
    "Shop ownership and restoration"
  ]
};s.AENativeCoverage=value;if(typeof module!=="undefined")module.exports=value;})(globalThis);
